### PR TITLE
[Reviewer: BJR2] Stats to csv

### PR DESCRIPTION
**Pull request by GAB-MS**
This PR modifies the stats_to_dita.py file so that it can also output a .csv file.

This is done by an optional '--output-csv' flag. If this is included on the script call, it will output a csv file instead.

This involved adding an extra `write_csv_file` function. A small snippet of code used in both `write_dita_table` and `write_csv_file` was commonised in the `get_data_from_stat` function.

As part of these changes, I also found and fixed a _potential_ bug. For 'intermediate' nodes, we looked for "N/A" in the `DESCRIPTION` field - but when generating test files (both DITA and .csv), I noticed entries that looked like intermediate nodes with "N/A" in the `MAX-ACCESS` field instead. It looked to me like this is what we should be looking for, so I made the change. This _might not_ be correct and should be verified before this PR is fully approved and merged.

The script passes all flake8 validation (this involved some extra whitespace additions) and both DITA and .csv output looks correct.

### CODE REVIEW

**Comment by benritchie** [comment]
Chris
This is George' code for adding CSV stats.  As discussed, sending over to you, to use when you work on improving this area.  
The one bit of feedback I was going to make on it was that I think we should be outputting more column's, in both the docs, and the CSV, than we currently do - we should be adding at least a datatype column.  
 - although sadly, I don't think that's straightforward, as some of our data types are enum like (e.g. SIP method)... - not quite sure how we'd handle these...

**Comment by GAB-MS** [comment]
@chris-elford-metaswitch  where's this at currently? Jenkins is complaining to me daily that this branch is stale; do you intend to make use of it in the future? If so, I need to add it to the stale branch whitelist.

**Comment by chris-elford-metaswitch** [comment]
I'm planning to use this in our next sprint. Can you go ahead and add it please?

**Comment by GAB-MS** [comment]
Okay, I've added it to the stale branch exclusion list. Please let me know when you're finished with the branch, so I can remove it from the list!

**Pull request merged**
