### PR TITLE
[Reviewer Ellie] Build errors

### PR DESCRIPTION
**Pull request by chris-elford-metaswitch**
Ellie, can you please review my attached fixes. The threading code here is a little fragile, with plenty of co-operation, but I don't see a simple alternative.

@johadalin you've been reviewing the rest of this so please take a look.

### CODE REVIEW

**Comment by chris-elford-metaswitch** [comment]
You're looking into this a bit more closely. The Jenkins tests are failing intermittently so it would be good to get this fixed up soon. However, the issue is with the UTs not the product code.

**Comment by eleanor-merry** [comment]
We've discussed this, assigning back to you

**Comment by chris-elford-metaswitch** [comment]
@eleanor-merry In our conversation, you are worried about a few of things in the current design/code:
- Changing the production code in such an artificial way to make it more testable.
- An overly complicated threading model - why not just let the alarm_manager start at startup and stop at exit?
- Can we simplify the logic in the run loop in the AlarmManager to make it simpler, safer, and easier to test.
- Is FV testing more appropriate for the run-loop logic?

You also have a concern about my use of exceptions in the MultiSeverityAlarm, which we haven't yet resolved.

I'd like to address all of these if possible, but I'm not going to be able to this week, and I'd like to leave the UTs in a state where they don't fail intermittently. Do you agree that I should merge this, and come back and tackle the technical debt later, or do you think there is a better way of handling this?

**Comment by eleanor-merry** [comment]
Ok, happy for you to merge this

**Pull request merged**
